"""Pydantic Schemas for Formal Investigation Graph & Epistemic Bayesian Reasoning."""
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class BeliefState(str, Enum):
    UNTESTED = "untested"
    WEAKENED = "weakened"
    SUPPORTED = "supported"
    HIGHLY_LIKELY = "highly_likely"
    REFUTED = "refuted"


class UnknownVariableNode(BaseModel):
    """Specific empirical parameters or unknowns being identified."""
    variable_name: str
    target_metric: str
    dimension_scope: Optional[str] = None
    prior_estimate: Optional[str] = None
    posterior_estimate: Optional[str] = None
    uncertainty_range: Optional[str] = None


class CandidateTestNode(BaseModel):
    """Specific candidate analytical experiment ranked by dynamically computed expected information gain and utility."""
    test_id: str
    hypothesis_id: str
    tool_name: str
    arguments: Dict[str, Any] = Field(default_factory=dict)
    rationale: str
    expected_uncertainty_reduction: float = Field(default=0.5, description="Expected delta entropy between 0.0 and 1.0")
    test_cost: float = Field(default=0.1, description="Normalized computational and latency cost")
    test_reliability: float = Field(default=0.9, description="Tool accuracy and signal-to-noise ratio")
    utility_score: float = Field(default=0.75, description="Computed as (ExpectedUncertaintyReduction * Reliability) / Cost")


class InvestigationHypothesisNode(BaseModel):
    """Formal hypothesis node in the investigation DAG with Bayesian likelihood updating."""
    id: str
    statement: str
    rationale: str
    prior_probability: float = Field(default=0.5, description="Prior belief P(H_i)")
    posterior_probability: float = Field(default=0.5, description="Current updated belief P(H_i | E)")
    belief_state: BeliefState = BeliefState.UNTESTED
    is_counter_hypothesis: bool = Field(default=False, description="True if generated by adversarial critique")
    falsifiable_predictions: List[str] = Field(default_factory=list)
    supporting_evidence_ids: List[str] = Field(default_factory=list)
    contradicting_evidence_ids: List[str] = Field(default_factory=list)
    last_evidence_likelihood: Optional[float] = Field(default=None, description="P(E | H_i)")
    reason_for_rejection: Optional[str] = None


class InvestigationGraphSchema(BaseModel):
    """Complete epistemological DAG representing the single unified investigation state."""
    objective: str
    target_variable: str
    unknowns: List[UnknownVariableNode] = Field(default_factory=list)
    hypotheses: List[InvestigationHypothesisNode] = Field(default_factory=list)
    candidate_tests: List[CandidateTestNode] = Field(default_factory=list)
    completed_tests: List[str] = Field(default_factory=list)
    entropy_current: float = Field(default=1.0, description="Current Shannon entropy / uncertainty across hypotheses")
    stopping_criteria_met: bool = False
    stopping_rationale: Optional[str] = None
