"""sync_orm_models_with_migrations

Revision ID: 9c1c76a818a4
Revises: 001_canonical_aaos
Create Date: 2026-08-29 18:34:04.909975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c1c76a818a4'
down_revision: Union[str, None] = '001_canonical_aaos'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_project_id'), 'audit_logs', ['project_id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_org_id'), 'projects', ['org_id'], unique=False)
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_table('alert_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('metric_name', sa.String(length=255), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('threshold_pct_change', sa.Float(), nullable=True),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('auto_investigate', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_evaluated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_project_id'), 'alert_rules', ['project_id'], unique=False)
    op.create_table('analysis_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('direct_answer', sa.Text(), nullable=True),
    sa.Column('main_finding', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(length=50), nullable=True),
    sa.Column('hypotheses_json', sa.JSON(), nullable=True),
    sa.Column('steps_json', sa.JSON(), nullable=True),
    sa.Column('findings_json', sa.JSON(), nullable=True),
    sa.Column('evidence_json', sa.JSON(), nullable=True),
    sa.Column('manifest_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_runs_project_id'), 'analysis_runs', ['project_id'], unique=False)
    op.create_table('business_glossary',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('synonyms_json', sa.JSON(), nullable=True),
    sa.Column('related_metrics_json', sa.JSON(), nullable=True),
    sa.Column('related_columns_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_glossary_project_id'), 'business_glossary', ['project_id'], unique=False)
    op.create_table('business_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sql_formula', sa.Text(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('dimensions_json', sa.JSON(), nullable=True),
    sa.Column('filters', sa.Text(), nullable=True),
    sa.Column('synonyms_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_metrics_project_id'), 'business_metrics', ['project_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_project_id'), 'conversations', ['project_id'], unique=False)
    op.create_table('dashboards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('widgets_json', sa.JSON(), nullable=True),
    sa.Column('filters_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboards_project_id'), 'dashboards', ['project_id'], unique=False)
    op.create_table('datasets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('column_count', sa.Integer(), nullable=True),
    sa.Column('data_quality_score', sa.Float(), nullable=True),
    sa.Column('profile_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_project_id'), 'datasets', ['project_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=True),
    sa.Column('executive_summary_json', sa.JSON(), nullable=True),
    sa.Column('technical_report_json', sa.JSON(), nullable=True),
    sa.Column('markdown_content', sa.Text(), nullable=False),
    sa.Column('pdf_artifact_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_project_id'), 'reports', ['project_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('alert_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('expected_value', sa.Float(), nullable=False),
    sa.Column('deviation_percentage', sa.Float(), nullable=False),
    sa.Column('affected_dimensions_json', sa.JSON(), nullable=True),
    sa.Column('investigation_analysis_id', sa.String(length=64), nullable=True),
    sa.Column('evidence_summary', sa.Text(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_events_project_id'), 'alert_events', ['project_id'], unique=False)
    op.create_table('dataset_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('column_count', sa.Integer(), nullable=True),
    sa.Column('transformation_applied', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_versions_dataset_id'), 'dataset_versions', ['dataset_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('sender_role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('analysis_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('organization_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_members_org_id'), 'organization_members', ['org_id'], unique=False)
    op.create_index(op.f('ix_organization_members_user_id'), 'organization_members', ['user_id'], unique=False)
    op.create_table('investigation_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('investigation_id', sa.String(length=64), nullable=False),
    sa.Column('execution_id', sa.String(length=64), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_payload_json', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('investigation_id', 'sequence', name='uq_investigation_event_seq')
    )
    op.create_index(op.f('ix_investigation_events_event_type'), 'investigation_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_investigation_events_execution_id'), 'investigation_events', ['execution_id'], unique=False)
    op.create_index(op.f('ix_investigation_events_investigation_id'), 'investigation_events', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_investigation_events_sequence'), 'investigation_events', ['sequence'], unique=False)
    op.create_index(op.f('ix_investigation_events_timestamp'), 'investigation_events', ['timestamp'], unique=False)
    op.create_table('investigation_executions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('investigation_id', sa.String(length=64), nullable=False),
    sa.Column('worker_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=True),
    sa.Column('current_step_index', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_executions_investigation_id'), 'investigation_executions', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_investigation_executions_status'), 'investigation_executions', ['status'], unique=False)
    op.create_index(op.f('ix_investigation_executions_worker_id'), 'investigation_executions', ['worker_id'], unique=False)
    op.create_table('investigation_jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('investigation_id', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('worker_id', sa.String(length=64), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_jobs_investigation_id'), 'investigation_jobs', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_investigation_jobs_lease_expires_at'), 'investigation_jobs', ['lease_expires_at'], unique=False)
    op.create_index(op.f('ix_investigation_jobs_priority'), 'investigation_jobs', ['priority'], unique=False)
    op.create_index(op.f('ix_investigation_jobs_status'), 'investigation_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_investigation_jobs_worker_id'), 'investigation_jobs', ['worker_id'], unique=False)
    op.create_table('investigation_decision_requests',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('investigation_id', sa.String(length=64), nullable=False),
    sa.Column('execution_id', sa.String(length=64), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options_json', sa.JSON(), nullable=True),
    sa.Column('default_action', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('user_response', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['investigation_executions.id'], ),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_decision_requests_execution_id'), 'investigation_decision_requests', ['execution_id'], unique=False)
    op.create_index(op.f('ix_investigation_decision_requests_investigation_id'), 'investigation_decision_requests', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_investigation_decision_requests_status'), 'investigation_decision_requests', ['status'], unique=False)
    op.create_table('investigation_resource_waits',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('investigation_id', sa.String(length=64), nullable=False),
    sa.Column('execution_id', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('required_capabilities_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('satisfied_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['investigation_executions.id'], ),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_resource_waits_execution_id'), 'investigation_resource_waits', ['execution_id'], unique=False)
    op.create_index(op.f('ix_investigation_resource_waits_investigation_id'), 'investigation_resource_waits', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_investigation_resource_waits_status'), 'investigation_resource_waits', ['status'], unique=False)
    op.create_table('investigation_step_executions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('execution_id', sa.String(length=64), nullable=False),
    sa.Column('investigation_id', sa.String(length=64), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(length=50), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('input_hash', sa.String(length=128), nullable=True),
    sa.Column('output_hash', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['investigation_executions.id'], ),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_step_executions_execution_id'), 'investigation_step_executions', ['execution_id'], unique=False)
    op.create_index(op.f('ix_investigation_step_executions_idempotency_key'), 'investigation_step_executions', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_investigation_step_executions_investigation_id'), 'investigation_step_executions', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_belief_updates_evidence_id'), 'belief_updates', ['evidence_id'], unique=False)
    op.add_column('evidence', sa.Column('evidence_type', sa.String(length=50), nullable=True))
    op.add_column('evidence', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('experiments', sa.Column('target_prediction_id', sa.String(length=64), nullable=True))
    op.add_column('experiments', sa.Column('adversarial_value', sa.Float(), nullable=True))
    op.add_column('experiments', sa.Column('robustness_value', sa.Float(), nullable=True))
    op.add_column('experiments', sa.Column('causal_value', sa.Float(), nullable=True))
    op.add_column('experiments', sa.Column('selection_rationale', sa.Text(), nullable=True))
    op.add_column('experiments', sa.Column('fingerprint', sa.String(length=64), nullable=True))
    op.add_column('experiments', sa.Column('replication_of', sa.String(length=64), nullable=True))
    op.add_column('experiments', sa.Column('refinement_of', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_experiments_fingerprint'), 'experiments', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_experiments_target_prediction_id'), 'experiments', ['target_prediction_id'], unique=False)
    op.add_column('hypotheses', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('hypotheses', sa.Column('supporting_prediction_count', sa.Integer(), nullable=True))
    op.add_column('hypotheses', sa.Column('refuted_prediction_count', sa.Integer(), nullable=True))
    op.add_column('hypotheses', sa.Column('unresolved_prediction_count', sa.Integer(), nullable=True))
    op.add_column('hypotheses', sa.Column('target_metric', sa.String(length=100), nullable=True))
    op.add_column('hypotheses', sa.Column('target_dimension', sa.String(length=100), nullable=True))
    op.add_column('hypotheses', sa.Column('target_value', sa.String(length=255), nullable=True))
    op.add_column('hypotheses', sa.Column('mechanism_detail', sa.Text(), nullable=True))
    op.add_column('hypotheses', sa.Column('generated_reason', sa.Text(), nullable=True))
    op.add_column('hypotheses', sa.Column('source_evidence_json', sa.JSON(), nullable=True))
    op.add_column('hypotheses', sa.Column('parent_hypotheses_json', sa.JSON(), nullable=True))
    # SQLite has no native ALTER COLUMN; batch mode recreates the table under
    # the hood so this migration runs identically on SQLite and Postgres.
    with op.batch_alter_table('investigation_verdicts', schema=None) as batch_op:
        batch_op.alter_column('epistemic_grade',
                   existing_type=sa.VARCHAR(length=10),
                   type_=sa.String(length=20),
                   existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_investigation_verdicts_investigation_id'))
        batch_op.create_index(batch_op.f('ix_investigation_verdicts_investigation_id'), ['investigation_id'], unique=True)
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.alter_column('status',
                   existing_type=sa.VARCHAR(length=50),
                   nullable=True)
        batch_op.alter_column('verdict_type',
                   existing_type=sa.VARCHAR(length=50),
                   nullable=True)
        batch_op.create_index(batch_op.f('ix_investigations_status'), ['status'], unique=False)
    op.add_column('predictions', sa.Column('investigation_id', sa.String(length=64), nullable=True))
    op.add_column('predictions', sa.Column('prediction_code', sa.String(length=50), nullable=True))
    op.add_column('predictions', sa.Column('target_metric', sa.String(length=100), nullable=True))
    op.add_column('predictions', sa.Column('target_dimension', sa.String(length=100), nullable=True))
    op.add_column('predictions', sa.Column('target_segment', sa.String(length=100), nullable=True))
    op.add_column('predictions', sa.Column('expected_value', sa.String(length=100), nullable=True))
    op.add_column('predictions', sa.Column('threshold', sa.Float(), nullable=True))
    op.add_column('predictions', sa.Column('expected_relationship', sa.String(length=255), nullable=True))
    op.add_column('predictions', sa.Column('expected_effect', sa.String(length=100), nullable=True))
    op.add_column('predictions', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('predictions', sa.Column('testability', sa.Boolean(), nullable=True))
    op.add_column('predictions', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('predictions', sa.Column('actual_observed_result_json', sa.JSON(), nullable=True))
    op.add_column('predictions', sa.Column('evaluation_reason', sa.Text(), nullable=True))
    op.add_column('predictions', sa.Column('target_experiment_id', sa.String(length=64), nullable=True))
    op.add_column('predictions', sa.Column('evaluated_at', sa.DateTime(), nullable=True))
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.alter_column('id',
                   existing_type=sa.VARCHAR(length=36),
                   type_=sa.String(length=64),
                   existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_predictions_investigation_id'), ['investigation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_status'), ['status'], unique=False)
        batch_op.create_foreign_key('fk_predictions_investigation_id', 'investigations', ['investigation_id'], ['id'])
    with op.batch_alter_table('semantic_business_rules', schema=None) as batch_op:
        batch_op.alter_column('rule_type',
                   existing_type=sa.VARCHAR(length=100),
                   nullable=True)
    with op.batch_alter_table('semantic_models', schema=None) as batch_op:
        batch_op.alter_column('status',
                   existing_type=sa.VARCHAR(length=50),
                   nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semantic_models', schema=None) as batch_op:
        batch_op.alter_column('status',
                   existing_type=sa.VARCHAR(length=50),
                   nullable=False)
    with op.batch_alter_table('semantic_business_rules', schema=None) as batch_op:
        batch_op.alter_column('rule_type',
                   existing_type=sa.VARCHAR(length=100),
                   nullable=False)
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_predictions_investigation_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_predictions_status'))
        batch_op.drop_index(batch_op.f('ix_predictions_investigation_id'))
        batch_op.alter_column('id',
                   existing_type=sa.String(length=64),
                   type_=sa.VARCHAR(length=36),
                   existing_nullable=False)
    op.drop_column('predictions', 'evaluated_at')
    op.drop_column('predictions', 'target_experiment_id')
    op.drop_column('predictions', 'evaluation_reason')
    op.drop_column('predictions', 'actual_observed_result_json')
    op.drop_column('predictions', 'status')
    op.drop_column('predictions', 'testability')
    op.drop_column('predictions', 'confidence')
    op.drop_column('predictions', 'expected_effect')
    op.drop_column('predictions', 'expected_relationship')
    op.drop_column('predictions', 'threshold')
    op.drop_column('predictions', 'expected_value')
    op.drop_column('predictions', 'target_segment')
    op.drop_column('predictions', 'target_dimension')
    op.drop_column('predictions', 'target_metric')
    op.drop_column('predictions', 'prediction_code')
    op.drop_column('predictions', 'investigation_id')
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investigations_status'))
        batch_op.alter_column('verdict_type',
                   existing_type=sa.VARCHAR(length=50),
                   nullable=False)
        batch_op.alter_column('status',
                   existing_type=sa.VARCHAR(length=50),
                   nullable=False)
    with op.batch_alter_table('investigation_verdicts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investigation_verdicts_investigation_id'))
        batch_op.create_index(batch_op.f('ix_investigation_verdicts_investigation_id'), ['investigation_id'], unique=False)
    with op.batch_alter_table('investigation_verdicts', schema=None) as batch_op:
        batch_op.alter_column('epistemic_grade',
                   existing_type=sa.String(length=20),
                   type_=sa.VARCHAR(length=10),
                   existing_nullable=True)
    op.drop_column('hypotheses', 'parent_hypotheses_json')
    op.drop_column('hypotheses', 'source_evidence_json')
    op.drop_column('hypotheses', 'generated_reason')
    op.drop_column('hypotheses', 'mechanism_detail')
    op.drop_column('hypotheses', 'target_value')
    op.drop_column('hypotheses', 'target_dimension')
    op.drop_column('hypotheses', 'target_metric')
    op.drop_column('hypotheses', 'unresolved_prediction_count')
    op.drop_column('hypotheses', 'refuted_prediction_count')
    op.drop_column('hypotheses', 'supporting_prediction_count')
    op.drop_column('hypotheses', 'status')
    op.drop_index(op.f('ix_experiments_target_prediction_id'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_fingerprint'), table_name='experiments')
    op.drop_column('experiments', 'refinement_of')
    op.drop_column('experiments', 'replication_of')
    op.drop_column('experiments', 'fingerprint')
    op.drop_column('experiments', 'selection_rationale')
    op.drop_column('experiments', 'causal_value')
    op.drop_column('experiments', 'robustness_value')
    op.drop_column('experiments', 'adversarial_value')
    op.drop_column('experiments', 'target_prediction_id')
    op.drop_column('evidence', 'confidence_score')
    op.drop_column('evidence', 'evidence_type')
    op.drop_index(op.f('ix_belief_updates_evidence_id'), table_name='belief_updates')
    op.drop_index(op.f('ix_investigation_step_executions_investigation_id'), table_name='investigation_step_executions')
    op.drop_index(op.f('ix_investigation_step_executions_idempotency_key'), table_name='investigation_step_executions')
    op.drop_index(op.f('ix_investigation_step_executions_execution_id'), table_name='investigation_step_executions')
    op.drop_table('investigation_step_executions')
    op.drop_index(op.f('ix_investigation_resource_waits_status'), table_name='investigation_resource_waits')
    op.drop_index(op.f('ix_investigation_resource_waits_investigation_id'), table_name='investigation_resource_waits')
    op.drop_index(op.f('ix_investigation_resource_waits_execution_id'), table_name='investigation_resource_waits')
    op.drop_table('investigation_resource_waits')
    op.drop_index(op.f('ix_investigation_decision_requests_status'), table_name='investigation_decision_requests')
    op.drop_index(op.f('ix_investigation_decision_requests_investigation_id'), table_name='investigation_decision_requests')
    op.drop_index(op.f('ix_investigation_decision_requests_execution_id'), table_name='investigation_decision_requests')
    op.drop_table('investigation_decision_requests')
    op.drop_index(op.f('ix_investigation_jobs_worker_id'), table_name='investigation_jobs')
    op.drop_index(op.f('ix_investigation_jobs_status'), table_name='investigation_jobs')
    op.drop_index(op.f('ix_investigation_jobs_priority'), table_name='investigation_jobs')
    op.drop_index(op.f('ix_investigation_jobs_lease_expires_at'), table_name='investigation_jobs')
    op.drop_index(op.f('ix_investigation_jobs_investigation_id'), table_name='investigation_jobs')
    op.drop_table('investigation_jobs')
    op.drop_index(op.f('ix_investigation_executions_worker_id'), table_name='investigation_executions')
    op.drop_index(op.f('ix_investigation_executions_status'), table_name='investigation_executions')
    op.drop_index(op.f('ix_investigation_executions_investigation_id'), table_name='investigation_executions')
    op.drop_table('investigation_executions')
    op.drop_index(op.f('ix_investigation_events_timestamp'), table_name='investigation_events')
    op.drop_index(op.f('ix_investigation_events_sequence'), table_name='investigation_events')
    op.drop_index(op.f('ix_investigation_events_investigation_id'), table_name='investigation_events')
    op.drop_index(op.f('ix_investigation_events_execution_id'), table_name='investigation_events')
    op.drop_index(op.f('ix_investigation_events_event_type'), table_name='investigation_events')
    op.drop_table('investigation_events')
    op.drop_index(op.f('ix_organization_members_user_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_org_id'), table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_dataset_versions_dataset_id'), table_name='dataset_versions')
    op.drop_table('dataset_versions')
    op.drop_index(op.f('ix_alert_events_project_id'), table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_reports_project_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_datasets_project_id'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_dashboards_project_id'), table_name='dashboards')
    op.drop_table('dashboards')
    op.drop_index(op.f('ix_conversations_project_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_business_metrics_project_id'), table_name='business_metrics')
    op.drop_table('business_metrics')
    op.drop_index(op.f('ix_business_glossary_project_id'), table_name='business_glossary')
    op.drop_table('business_glossary')
    op.drop_index(op.f('ix_analysis_runs_project_id'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index(op.f('ix_alert_rules_project_id'), table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_org_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_audit_logs_project_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
